export const USER_UI_START_LOADING = 'USER_UI_START_LOADING';
export const USER_UI_STOP_LOADING = 'USER_UI_STOP_LOADING';
export const RANKS_UI_START_LOADING = 'RANKS_UI_START_LOADING';
export const RANKS_UI_STOP_LOADING = 'RANKS_UI_STOP_LOADING';
export const SPECIALIZATIONS_UI_START_LOADING = 'SPECIALIZATIONS_UI_START_LOADING';
export const SPECIALIZATIONS_UI_STOP_LOADING = 'SPECIALIZATIONS_UI_STOP_LOADING';
export const LECTURERS_UI_START_LOADING = 'LECTURERS_UI_START_LOADING';
export const LECTURERS_UI_STOP_LOADING = 'LECTURERS_UI_STOP_LOADING';
export const COURSES_UI_START_LOADING = 'COURSES_UI_START_LOADING';
export const COURSES_UI_STOP_LOADING = 'COURSES_UI_STOP_LOADING';
export const DEPARTMENTS_UI_START_LOADING = 'DEPARTMENTS_UI_START_LOADING';
export const DEPARTMENTS_UI_STOP_LOADING = 'DEPARTMENTS_UI_STOP_LOADING';

export const SET_TOKEN = 'SET_TOKEN';

export const SET_USER = 'SET_USER';

export const SET_RANKS = 'SET_RANKS';

export const SET_SPECIALIZATIONS = 'SET_SPECIALIZATIONS';

export const SET_LECTURERS = 'SET_LECTURERS';

export const SET_COURSES = 'SET_COURSES';

export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';
